# Generated by Django 3.2.5 on 2024-01-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0002_dweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='dweet',
            name='cover',
            field=models.ImageField(default='logo+header.png', upload_to='../media/images/'),
        ),
    ]
