# Generated by Django 3.2.5 on 2024-01-07 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0003_alter_dweet_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dweet',
            old_name='cover',
            new_name='image',
        ),
    ]
